version: '3'
services:
  payments-service:
    image: payment-platform:1.0
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_USERNAME=admin
      - MONGO_PASSWORD=password
    ports:
      - "8080:8080"
    depends_on:
      - mongo
  mongo:
    image: mongo:4.0
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password