apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-platform-deployment
  labels:
    app: payment-platform
spec:
  replicas: 3
  selector:
    matchLabels:
      app: payment-platform
  template:
    metadata:
      labels:
        app: payment-platform
    spec:
      volumes:
        - name: db-connection-secrets
          secret:
            secretName: db-connection-secrets
            optional: false
      containers:
        - name: app
          image: bogdanjava/payment-platform:latest
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_PORT
              valueFrom:
                secretKeyRef:
                  name: db-connection-secrets
                  key: mongoPort
                  optional: false
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-connection-secrets
                  key: mongoPassword
                  optional: false
            - name: MONGO_HOST
              valueFrom:
                secretKeyRef:
                  name: db-connection-secrets
                  key: mongoHost
                  optional: false
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-connection-secrets
                  key: mongoUsername
                  optional: false

