apiVersion: v1
kind: Service
metadata:
  name: payment-platform
spec:
  type: NodePort
  selector:
    app: payment-platform
  ports:
    - protocol: TCP
      port: 8070
      targetPort: 8080
      nodePort: 30007