# This is a basic workflow to help you get started with Actions

name: CI

on: [ push ]

jobs:

  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Run tests
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: test
      - name: Build Jar
        run: ./gradlew :bootJar
      - name: Archive Jar
        uses: actions/upload-artifact@v3
        with:
          name: app-jar
          path: build/libs/app.jar

  build-docker:
    environment:
      name: default
    needs: test-and-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: app-jar
          path: artifacts/
      - name: Copy the Jar file to the project directory
        run: ls -la artifacts && pwd
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build the Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: bogdanjava/payments-platform:latest



